### ISSUE TITLE
Verbose Name, Help Text appears as references and not actual text

### ISSUE THREAD

**Issue by expresspotato** [boxine/django-huey-monitor#7]
Nice Library, the verbose name and help text appears as references and not actual text on many fields.

![Capture003](https://user-images.githubusercontent.com/4267949/102406572-c1082180-3fb8-11eb-81fd-881901518459.PNG)

**Comment by jedie** [comment]
This is already fixed in master.

**Comment by expresspotato** [comment]
Hi Jedie, 

Thanks, but we're still seeing this issue:

![Capture](https://user-images.githubusercontent.com/4267949/112408490-46088280-8cee-11eb-8961-6614eed0f278.PNG)

**Comment by jedie** [comment]
Think you don't has "bx_py_utils" in your INSTALLED_APPS, isn't it?
See: https://github.com/boxine/django-huey-monitor#quickstart

The times are the last update of every entry. See the content of the tooltip.
